services:
  database:
    image: postgres
    volumes:
      - app-database:/var/lib/postgresql/data:Z
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watcher_crm

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - buildno
        - gitcommithash
    depends_on:
      - database
    tmpfs:
      - /app/tmp:uid=1000,gid=1000
    volumes:
      - app-logs:/app/logs:uid=1000,gid=1000
      - app-acme:/acme
    working_dir: /app/
    restart: always
    environment:
      DATABASE_URL: postgres://postgres@database/watcher_crm
    ports:
      - 80:80/tcp
      - 443:443/tcp

volumes:
  app-database:
  app-logs:
  app-acme:
