services:
  webserver-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev-frankenphp
      args:
        - buildno
        - gitcommithash
    depends_on:
      - database-dev
      - cache-dev
    tmpfs:
      - /app/logs:uid=1000,gid=1000
      - /app/tmp:uid=1000,gid=1000
      - /app/vendor:uid=1000,gid=1000,exec
      - /app/node_modules:uid=1000,gid=1000,exec
    volumes:
      - ./:/app
    working_dir: /app/
    environment:
      DATABASE_URL: postgres://postgres@database-dev/watcher_crm
      DATABASE_RADIUS_URL: postgres://postgres@database-dev/watcher_crm_radius
      DATABASE_RUIAN_URL: postgres://postgres@database-dev/watcher_crm_ruian
      CACHE_DURATION: "${CACHE_DURATION:-+2 minutes}"
      CACHE_DEFAULT_URL: "redis://cache-dev:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_default_&duration=${CACHE_DURATION:-+2 minutes}"
      CACHE_CAKECORE_URL: "redis://cache-dev:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_cake_core_&duration=${CACHE_DURATION:-+2 minutes}"
      CACHE_CAKEMODEL_URL: "redis://cache-dev:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_cake_model_&duration=${CACHE_DURATION:-+2 minutes}"
      CACHE_APICLIENT_URL: "redis://cache-dev:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_api_client_&duration=${CACHE_DURATION:-+2 minutes}"
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 443:443/udp # HTTP/3
    tty: true

  database-dev:
    image: postgres:18
    tmpfs:
      - /var/lib/postgresql:exec
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watcher_crm
    ports:
      - 5432:5432/tcp

  cache-dev:
    image: redis:alpine
    tmpfs: 
      - /data:exec
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
