services:
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
      args:
        - buildno
        - gitcommithash
    depends_on:
      - database
      - cache
    tmpfs:
      - /app/tmp:uid=1000,gid=1000
    volumes:
      - app-logs:/app/logs:uid=1000,gid=1000
      - app-acme:/acme
    working_dir: /app/
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres@database/watcher_crm
      CACHE_DURATION: "${CACHE_DURATION:-+10 days}"
      CACHE_DEFAULT_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_default_&duration=${CACHE_DURATION:-+10 days}"
      CACHE_CAKECORE_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_cake_core_&duration=${CACHE_DURATION:-+10 days}"
      CACHE_CAKEMODEL_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_cake_model_&duration=${CACHE_DURATION:-+10 days}"
      CACHE_APICLIENT_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_api_client_&duration=${CACHE_DURATION:-+10 minutes}"
      CACHE_ADDRESSES_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_api_addresses_&duration=${CACHE_DURATION:-+10 days}"
      CACHE_BUSINESS_REGISTER_URL: "redis://cache:6379/?database=0&password=redis&prefix=${APP_NAME:-localhost}_business_register_&duration=${CACHE_DURATION:-+10 days}"
      SERVER_NAME: ${APP_NAME:-localhost} # Set to your domain in production (for ACME certificate issuance)
    env_file:
      - ./config/.env
    ports:
      - 80:80/tcp
      - 443:443/tcp

  database:
    image: postgres:18
    volumes:
      - app-database:/var/lib/postgresql:Z
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watcher_crm

  cache:
    image: redis:alpine
    volumes: 
      - app-cache:/data
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis

volumes:
  app-database:
  app-cache:
  app-logs:
  app-acme:
