services:
  database-dev:
    image: postgres
    tmpfs:
      - /var/lib/postgresql/data:exec
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watcher_crm
    ports:
      - 5432:5432/tcp

  webserver-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - buildno
        - gitcommithash
    depends_on:
      - database-dev
    tmpfs:
      - /app/logs:uid=1000,gid=1000
      - /app/tmp:uid=1000,gid=1000
      - /app/vendor:uid=1000,gid=1000,exec
    volumes:
      - ./:/app
    working_dir: /app/
    environment:
      DATABASE_URL: postgres://postgres@database-dev/watcher_crm
      DATABASE_RADIUS_URL: postgres://postgres@database-dev/watcher_crm_radius
      DATABASE_RUIAN_URL: postgres://postgres@database-dev/watcher_crm_ruian
    ports:
      - 80:80/tcp
