# syntax=docker/dockerfile:1

FROM webdevops/php-nginx:8.3-alpine

ARG buildno
ARG gitcommithash

RUN echo "Build number: $buildno"
RUN echo "Based on commit: $gitcommithash"

ENV DEBUG "true"
ENV WEB_DOCUMENT_ROOT "/app/webroot"

# Install ping command
RUN set -x \
 && apk add -U --no-cache iputils \
 && docker-image-cleanup

# Install PECL-DBASE extension
RUN set -x \
 && apk add -U --no-cache autoconf gcc libc-dev make \
 && CPPFLAGS="-DHAVE_SYS_FILE_H" pecl install dbase \
 && docker-php-ext-enable dbase \
 && docker-run-bootstrap \
 && docker-image-cleanup

# Add on-start commands
RUN echo '# Composer oprations' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer install -d /app' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer run-script migrations -d /app -- --no-lock' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer run-script schema-cache -d /app' >> /opt/docker/provision/entrypoint.d/99-composer.sh
