<?php
/**
 * Bookkeeping plugin — default settings (baseline template).
 *
 * This file provides the Bookkeeping plugin's baseline configuration values that
 * the SettingsService loads as a fallback when no value is stored in the database.
 * Treat these values as a TEMPLATE / reference example — not as your live config.
 *
 * HOW TO CUSTOMIZE (IMPORTANT):
 * Do NOT edit this file to configure your installation. It is versioned and may be
 * overwritten on upgrades, so changes made here can be lost. Instead, override the
 * values you need in the database via the Settings UI (or programmatically through
 * SettingsService::set()). Database overlays always take precedence over these
 * defaults (priority: DB > defaults).
 *
 * The shipped values are oriented to a Czech (CZ) company and serve as a working
 * example. Tailor them to your own organization through the settings UI.
 *
 * Structure:
 * - The top-level key is this plugin's namespace ('bookkeeping').
 * - It holds one or more logical blocks (keys), which may contain nested values.
 * - Values can be scalars or arrays, and may use env() to allow environment-specific overrides.
 *
 * Notes:
 * - Secrets and credentials belong in environment variables, not in the database.
 * - This file is a declarative source of truth for default values only.
 * - A value that is not a plain scalar says what it is: wrap it in a SettingType
 *   (ListType, BoolType, ...). A declared setting is drawn accordingly in the
 *   settings UI, is checked before it is stored, and is overlaid whole rather
 *   than merged into item by item.
 * - Declare them with named arguments (default:, hint:, ...), so what each value
 *   is for can be read off the line it stands on.
 */

use Bookkeeping\Model\Enum\InvoicingSchedule;
use Bookkeeping\Provider\Eurofaktura\EurofakturaProvider;
use Bookkeeping\Provider\Pohoda\PohodaProvider;
use Settings\ValueObject\Type\BoolType;
use Settings\ValueObject\Type\ChoiceType;
use Settings\ValueObject\Type\ListType;
use Settings\ValueObject\Type\NumberType;

return [
    'bookkeeping' => [
        'accounting' => [

            // Default provider (pohoda / eurofaktura)
            'default_provider' => 'pohoda',

            // Accounting providers
            'providers' => [

                // -----------------------------------------
                // Stormware POHODA
                // -----------------------------------------
                'pohoda' => [
                    // Class name
                    'class' => PohodaProvider::class,

                    // API
                    'api' => [
                        'url' => (string)env('POHODA_MSERVER_URL', 'http://localhost:44444'),

                        // which accounting unit mServer is to answer for, named by its
                        // identity number - a test file is reached by naming a different one
                        'accounting_unit' => (string)env('POHODA_COMPANY_ID', '00000000'),

                        'timeout' => NumberType::ofInt(
                            default: 3600,
                            hint: __d('bookkeeping', 'How long to wait for the accounting API, in seconds.'),
                        ),
                    ],
                ],

                // -----------------------------------------
                // EUROFAKTURA / E‑RACUNI
                // -----------------------------------------
                'eurofaktura' => [
                    // Class name
                    'class' => EurofakturaProvider::class,

                    // Issuer metadata
                    'issuer' => [
                        'city' => 'Makarska',
                        'business_unit' => 'POSL1',
                        'business_year_format' => 'yyyy',
                    ],

                    // Invoices
                    'invoice' => [
                        'status' => 'Draft', // or 'IssuedInvoice'
                        'send_issued_invoice_by_email' => new BoolType(default: false),
                    ],

                    // Invoice items
                    'items' => [
                        'default_classification_code' => 'K61.10.00',
                    ],

                    // Documents
                    'document' => [
                        'currency' => 'EUR',
                        'language' => 'Croatian',
                    ],

                    // VAT / Reverse charge
                    'vat' => [
                        'clause' => 'Registered',
                        'transaction_type' => [
                            'standard' => '0',
                            'reverse_charge' => '14',
                        ],
                    ],

                    // Invoice types
                    'invoice_type' => [
                        'standard' => 'Retail',
                        'reverse_charge' => 'Gross',
                    ],

                    // Payments
                    'payment' => [
                        'method' => 'BankTransfer',
                        'reference_prefix' => '00 ',
                    ],

                    // Customers (sync)
                    'customers' => [
                        'use_buyer_code' => new BoolType(default: false),
                        'code_prefix' => '',
                    ],

                    // API
                    'api' => [
                        'url' => (string)env('EUROFAKTURA_API_URL', 'https://e-racuni.com/H7i/API'),
                        'timeout' => NumberType::ofInt(
                            default: 3600,
                            hint: __d('bookkeeping', 'How long to wait for the accounting API, in seconds.'),
                        ),
                    ],
                ],
            ],
        ],

        'invoices' => [
            'issuing' => [
                // When invoicing runs, and so which periods it has settled. Nothing in the data
                // says which months were invoiced, so this is what a billing is held against:
                // a date inside a settled period may no longer be moved.
                'schedule' => new ChoiceType(
                    default: InvoicingSchedule::CURRENT_MONTH_ON_LAST,
                    hint: __d(
                        'bookkeeping',
                        'Also the default the invoicing command takes when it is called without --schedule.',
                    ),
                ),

                // Whether the day of the run itself is still open. It usually is: the check
                // against the control file fails and it is put right on that very day.
                'day_stays_open' => new BoolType(
                    default: true,
                    hint: __d(
                        'bookkeeping',
                        'Leave the period being invoiced today open, so it can still be corrected.',
                    ),
                ),
            ],

            'texts' => [
                'default' => 'Faktura za poskytované služby dle smlouvy {contract_number} za období {invoiced_month}',
                'separate' => 'Faktura za službu {service_name} za období {invoiced_month}',
            ],
            'emails' => [
                'subject' => 'NETAIR - {invoice_text} - {invoice_number} - VS: {variable_symbol}',
                'body_text' => <<<TEXT
                    Vážený zákazníku,

                    dne {creation_date} Vám byla vystavena faktura - daňový doklad č. {invoice_number} splatná {due_date}.

                    Variabilní symbol pro platbu: {variable_symbol}
                    Číslo našeho účtu: {bank_account_number}
                    Celková částka (včetně DPH): {total_amount}

                    V příloze Vám zasíláme doklad ve formátu PDF.

                    Tuto i další námi vystavené faktury je možné stahovat i v našem Uživatelském portálu,
                    kde si zároveň můžete zkontrolovat, zda jsou uhrazeny.
                    Pokud si nepřejete dostávat faktury e-mailem, můžete si zde změnit i formu zasílání.

                    Uživatelský portál: {user_portal_url}

                    Tento email byl vygenerován automaticky.

                    {company_name}
                    {company_address_line_1}
                    {company_address_line_2}
                    IČ: {identity_number}, DIČ: {vat_number}
                    TEXT,
            ],
        ],

        'debtors' => [
            // Who is a debtor at all: how long a payment may be late, and how small a debt is
            // passed over.
            'thresholds' => [
                'allowed_payment_delay' => NumberType::ofInt(
                    default: (int)env('DEBTORS_ALLOWED_PAYMENT_DELAY', '0'),
                    hint: __d('bookkeeping', 'How many days a payment may be late before it counts.'),
                ),
                'allowed_total_overdue_debt' => NumberType::ofDecimal(
                    default: (float)env('DEBTORS_ALLOWED_TOTAL_OVERDUE_DEBT', '0'),
                    scale: 2,
                    hint: __d('bookkeeping', 'How small an overdue debt is passed over.'),
                ),
            ],

            'notifications' => [
                'enabled' => new BoolType(default: true), // global kill‑switch

                'days' => ListType::ofInts(
                    default: array_map(
                        intval(...),
                        array_filter(explode(',', (string)env('DEBTORS_NOTIFY_DAYS', '5,10'))),
                    ),
                    hint: __d(
                        'bookkeeping',
                        'How many days before the due date a debtor is warned on. An empty list [] warns on none.',
                    ),
                ),

                'channels' => [
                    'email' => [
                        'enabled' => new BoolType(default: true),
                    ],
                    'sms' => [
                        'enabled' => new BoolType(default: true),
                    ],
                ],
                'types' => [
                    'notify' => [
                        'enabled' => new BoolType(default: true),
                    ],
                    'block' => [
                        'enabled' => new BoolType(default: true),
                    ],
                    'inactive' => [
                        'enabled' => new BoolType(default: true),
                    ],
                ],
            ],
            'blocking' => [
                'enabled' => new BoolType(default: true), // global kill‑switch

                // the label a blocked customer is given; nothing named leaves them unlabelled
                'blocked_label_id' => (string)env('DEBTORS_BLOCKED_LABEL_ID', ''),

                'services' => [
                    'sledovani_tv' => [
                        'enabled' => new BoolType(default: true),
                    ],
                    'routers' => [
                        'enabled' => new BoolType(default: true),

                        // the firewall address list the blocked addresses are written into
                        'address_list' => (string)env('DEBTORS_ADDRESS_LIST', ''),
                    ],
                ],
            ],
            'tables' => [
                'invoices' => [
                    'headers' => [
                        'number' => 'Číslo faktury',
                        'variable_symbol' => 'Var. symbol',
                        'creation_date' => 'Datum',
                        'due_date' => 'Splatnost',
                        'total' => 'Cena',
                        'debt' => 'Dluh',
                    ],
                    'total_label' => 'Dluh celkem:',
                    'separator' => '-------------------------------------------------------------------------------------------',
                    'footer' => '===========================================================================================',
                ],
            ],
            'emails' => [
                'notify' => [
                    'subject' => 'NETAIR - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body_text' => <<<TEXT
                        Vážený zákazníku,

                        rádi bychom Vás upozornili, že k dnešnímu dni evidujeme neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}.

                        {invoices_table}

                        Pokud máte vše uhrazeno, kontaktujte nás prosím a sdělte nám datum, variabilní symbol a číslo účtu, ze kterého byly platby provedeny.

                        Pokud se jedná o nedoplatek, je to pravděpodobně způsobeno tím, že jste nedávno byli převedeni na nové tarify, o čemž jsme vás informovali e-mailem.

                        Kontakty na naše účetní oddělení
                        Mail: {company_invoices_email}
                        Telefon: {company_invoices_phone}
                        Číslo účtu: {bank_account_number}

                        Volat můžete od pondělí do pátku mezi 08:00-12:00 a 13:00-16:00.

                        Pokud Vám nepřichází faktury do emailu, zkontrolujte si prosím, zda jste odsouhlasili, že je chcete dostávat.
                        Potřebné souhlasy je možné udělit v sekci Uživatelské údaje, po přihlášení do Uživatelského portálu: {user_portal_url}
                        Pokud nemáte přihlašovací údaje, můžete si je vyžádat zde: https://netair.cz/podpora/zrizeni-pristupu-do-uzivatelskeho-portalu/

                        {company_name}
                        {company_address_line_1}
                        {company_address_line_2}
                        IČ: {identity_number}, DIČ: {vat_number}
                        TEXT,
                ],
                'block' => [
                    'subject' => 'NETAIR - pozastavení služeb - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body_text' => <<<TEXT
                        Vážený zákazníku,

                        rádi bychom Vás upozornili, že naše služby byly pozastaveny z důvodu neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}.

                        {invoices_table}

                        Pokud máte vše uhrazeno, kontaktujte nás prosím a sdělte nám datum, variabilní symbol a číslo účtu, ze kterého byly platby provedeny.

                        Kontakty na naše účetní oddělení
                        Mail: {company_invoices_email}
                        Telefon: {company_invoices_phone}
                        Číslo účtu: {bank_account_number}

                        Volat můžete od pondělí do pátku mezi 08:00-12:00 a 13:00-16:00.

                        Pokud Vám nepřichází faktury do emailu, zkontrolujte si prosím, zda jste odsouhlasili, že je chcete dostávat.
                        Potřebné souhlasy je možné udělit v sekci Uživatelské údaje, po přihlášení do Uživatelského portálu: {user_portal_url}
                        Pokud nemáte přihlašovací údaje, můžete si je vyžádat zde: https://netair.cz/podpora/zrizeni-pristupu-do-uzivatelskeho-portalu/

                        {company_name}
                        {company_address_line_1}
                        {company_address_line_2}
                        IČ: {identity_number}, DIČ: {vat_number}
                        TEXT,
                ],
                'inactive' => [
                    'subject' => 'NETAIR - neaktivní služby - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body_text' => <<<TEXT
                        Vážený zákazníku,

                        rádi bychom Vás upozornili, že k dnešnímu dni stále evidujeme neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}.

                        {invoices_table}

                        Pokud máte vše uhrazeno, kontaktujte nás prosím a sdělte nám datum, variabilní symbol a číslo účtu, ze kterého byly platby provedeny.

                        Kontakty na naše účetní oddělení
                        Mail: {company_invoices_email}
                        Telefon: {company_invoices_phone}
                        Číslo účtu: {bank_account_number}

                        Volat můžete od pondělí do pátku mezi 08:00-12:00 a 13:00-16:00.

                        Pokud Vám nepřichází faktury do emailu, zkontrolujte si prosím, zda jste odsouhlasili, že je chcete dostávat.
                        Potřebné souhlasy je možné udělit v sekci Uživatelské údaje, po přihlášení do Uživatelského portálu: {user_portal_url}
                        Pokud nemáte přihlašovací údaje, můžete si je vyžádat zde: https://netair.cz/podpora/zrizeni-pristupu-do-uzivatelskeho-portalu/

                        {company_name}
                        {company_address_line_1}
                        {company_address_line_2}
                        IČ: {identity_number}, DIČ: {vat_number}
                        TEXT,
                ],
            ],
            'sms' => [
                'notify' => [
                    'subject' => 'NETAIR - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body' => 'Vážený zákazníku, rádi bychom Vás upozornili, že k dnešnímu dni evidujeme neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}. Pokud máte vše uhrazeno, kontaktujte nás prosím (8:00-16:00). {company_name}, tel: {company_invoices_phone}, č.ú.: {bank_account_number}',
                ],
                'block' => [
                    'subject' => 'NETAIR - pozastavení služeb - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body' => 'Vážený zákazníku, naše služby byly pozastaveny z důvodu neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}. Pokud máte vše uhrazeno, kontaktujte nás prosím (8:00-16:00). {company_name}, tel: {company_invoices_phone}, č.ú.: {bank_account_number}',
                ],
                'inactive' => [
                    'subject' => 'NETAIR - neaktivní služby - neuhrazené pohledávky ke dni {date} - VS: {customer_number}',
                    'body' => 'Vážený zákazníku, rádi bychom Vás upozornili, že k dnešnímu dni stále evidujeme neuhrazené pohledávky po splatnosti ve výši {total_overdue_debt}, VS: {customer_number}. Pokud máte vše uhrazeno, kontaktujte nás prosím (8:00-16:00). {company_name}, tel: {company_invoices_phone}, č.ú.: {bank_account_number}',
                ],
            ],
        ],
    ],
];
